### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AibersonDev** [chxlls/economybot#11]
You could make a store system with quick.db, sometimes it is useful, and I tried to do it but it did not result.

**Comment by Coocktail** [comment]
The inventory system?

**Comment by AibersonDev** [comment]
Suppose there are commands like:
- additem
- store
and so on.

If the item is a role that is added to the user who bought the item. Command:
- buy

**Comment by chxlls** [comment]
I was actually going to make a command like this but dropped the whole project, it shouldn't be too hard but I'm not doing anything with this repo anymore. Just there for people to go through and use if they want.
