### ISSUE TITLE
Problem running the commands?

### ISSUE THREAD

**Issue by ZrSenpaii** [chxlls/economybot#19]
I downloaded the zip and didnt really change anything in the code itself. 
I managed to get the bot started but he doens't react to any of the commands. He's just there, online. but not doing anything xD

**Comment by chxlls** [comment]
Get any errors?

**Comment by SpeedRacer07** [comment]
its with v11 so all places it should be message embed instead of rich embed developer needs to update this , can you please update the code and send

**Comment by chxlls** [comment]
I'm not updating this repo anymore, just here to answer issues sorry

**Comment by SpeedRacer07** [comment]
alright

**Comment by SpeedRacer07** [comment]
il try to update and if you allow i can publish

**Comment by chxlls** [comment]
Sweet, just make a pull request
