### ISSUE TITLE
Leaderboad.js

### ISSUE THREAD

**Issue by Itz-MrJ** [chxlls/economybot#21]
"**db.startsWith() is not a function.**" 
I had received an error as mentioned above, hence I removed that statement and altered it to **"let money = (`money_${message.guild.id}`, { sort: '.data'})"**. Worked properly, but the leaderboard has 0 values in it. (*Please refer the image attached.*)
![Screenshot 2021-01-27 at 9 28 59 AM](https://user-images.githubusercontent.com/68953408/105940837-294f2600-6082-11eb-883e-105655659427.png)

**Comment by nadzuwu** [comment]
instead of using  let money = db.startsWith(`money_${message.guild.id}`, { sort: '.data'}) use **let money = db.all(`money_${message.guild.id}`, { sort: '.data'})**. This worked for me.

**Comment by ghost** [comment]
use db.has instead of db.startsWith as it was deprecated
