### ISSUE TITLE
Prefix Issue

### ISSUE THREAD

**Issue by rockdude129** [chxlls/economybot#23]
My prefix is "m!". But when I do m!bal nothing happens.

**Comment by ghost** [comment]
@rockdude129 you go to help.js and change the Discord.RichEmbed() to Discord.MessageEmbed() that worked for me 
(fixed code below)
`const Discord = require('discord.js')
const db = require('quick.db')

module.exports.run = async (bot, message, args) => {
    if(!message.content.startsWith('m!'))return;  


    let embed = new Discord.MessageEmbed()
    .setTitle("Help Centre [Prefix m!]")
    .addField("Economy Commands", "`work` `beg` `rob` `pay` `balance` `profile` `withdraw` `deposit` `daily` `weekly` `store` `buy` `sell`")
    .addField("Gambling Commmands", "`roulette` `slots`")
    .addField("Economy Extra Commands", "`storeinfo [item]`")
    .setColor("#FFFFFF")
    message.channel.send(embed)




}

module.exports.help = {
  name:"help",
  aliases: [""]
}`

**Comment by ghost** [comment]
you also have to change EVERY FILE TO MessageEmbed() , not RichEmbed().

**Comment by rockdude129** [comment]
@strange-idiot every single thing that says RichEmbed()?????

**Comment by nandanp1** [comment]
now my prefix is r. and r.help is not working :(

**Comment by nandanp1** [comment]
nvm it works
