### ISSUE TITLE
The leaderboard doesn't work

### ISSUE THREAD

**Issue by Mr-aahir** [chxlls/economybot#29]
![image](https://user-images.githubusercontent.com/67744910/120426513-e08bde80-c38d-11eb-9acb-6138da28a798.png)

**Comment by Mr-aahir** [comment]
For all the leaderboards it is the same issue

**Comment by chxlls** [comment]
Because .startsWith is depricated in the most recent versions of quick.db. Try .all

**Comment by D4rkk1** [comment]
> Porque .startsWith está obsoleto nas versões mais recentes de quick.db. Experimente .todos

db.all or only .all?

**Comment by Tomato6966** [comment]
of course db.all
