### ISSUE TITLE
discord.richembed is not a constructor

### ISSUE THREAD

**Issue by strathabib** [chxlls/economybot#5]
ok so the bot comes online but when i go to use any command i get 
discord.richembed is not a constructor

**Comment by TheLastGamer18** [comment]
are you using a discord.js v12? Cause in v12 its MessageEmbed instead of RichEmbed

**Comment by BloodStainsTR** [comment]
İf you are using v11, just check if the embed value is Discord.RichEmbed()

**Comment by chxlls** [comment]
Make sure your DJS version is v11, if not then correct it accordingly to match v12.
