### ISSUE TITLE
Economy is only per guild

### ISSUE THREAD

**Issue by jeydinpham** [chxlls/economybot#8]
The economy is only for 1 server, is you invite the bot to another server with the same code, you now have 0 while on the other server you could have like thousands.

**Comment by chxlls** [comment]
Yea, it is saved per guild but you can change that around by removing the "message.guild.id" from the DB saving.

**Comment by jeydinpham** [comment]
I tried that too and it actually didn’t work for some reason. The correct solution is to do 

const db = require('quick.db')
var economy = new db.table('economy')

and therefore replace "db" with "economy."

**Comment by chxlls** [comment]
Might be a new update with quick.db, either way, happy that it has been sorted.

I am not going to update the commands but do feel free to submit a pull request.
