### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by Pool800** [chxlls/economybot#9]
what modules u usin?

**Comment by chxlls** [comment]
Just Discord.js & Quick.db

(There may be other modules such as MS being used but you will see it in the console when you try run the bot)

**Comment by Pool800** [comment]
Yah there was, I installed them but it still threw errors. Is there some sort of setup involved in using quick.db?

**Comment by Coocktail** [comment]
@Pool800 No not a lot

**Comment by Coocktail** [comment]
@Pool800 and which errors?
